version: 2
jobs:
  'hawkeye':
    docker:
      - image: hawkeyesec/scanner-cli
    steps:
      - run:
          name: Setup for hawkeye scan
          command: mkdir -p /tmp/artifacts/
      - checkout
      - run:
          name: Run Hawkeye Scan
          command: hawkeye scan --all --target ./ --fail-on critical --json /tmp/artifacts/hawkeye-findings.json
      - store_artifacts:
          path: /tmp/artifacts
  tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            sudo apt-get update
            sudo apt-get -y install mysql-server
            sudo service mysql start
            sudo sh .setup.sh
            npm i && npm run m-s-t

    environment:
      - ENV: test

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - hawkeye
      - tests
