version: 2
jobs:
  'hawkeye':
    docker:
      - image: hawkeyesec/scanner-cli
    steps:
      - run:
          name: Setup for hawkeye scan
          command: mkdir -p /tmp/artifacts/
      - checkout
      - run:
          name: Run Hawkeye Scan
          command: hawkeye scan --all --target ./ --fail-on critical --json /tmp/artifacts/hawkeye-findings.json
      - store_artifacts:
          path: /tmp/artifacts
  tests:
    working_directory: ~/repo
    docker:
      - image: circleci/mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: library_test
          MYSQL_USER: knowell
          MYSQL_PASSWORD:
    steps:
      - run:
          name: Running tests
          command: |
            apt-get update
            apt-get -y install node
            apt-get -y install npm
            npm run m-s-t

    environment:
      - ENV: test

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - hawkeye
      - tests
